name: hush
description: A Flutter plugin that prevents audio from being captured during screen recording on Android devices by using a secure audio path.
version: 0.0.1
homepage: https://github.com/munavv3r/hush
repository: https://github.com/munavv3r/hush

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hush.hush
        pluginClass: HushPlugin